export const products = [
    {
        image: require('../assets/images/Marlin7/Marlin7-1.webp'),
        name: "BICICLETA DE MONTAÑA MARLIN 7 - 2022",
        category: "bicicleta",
        description: "Es ideal para ti si eres nuevo en el sendero pero tienes aspiraciones serias de pista unica y quieres una bicicleta de montaña digna de una carrera con mejoras en las partes que marquen una gran diferencia en el rendimiento, como una horquilla de suspensión de mayor calidad y una transmisión de amplio rango 1x.. La tecnología que incorpora un cuadro ligero con cable de cambio interno y enrutamiento del cable de la manguera del freno, una horquilla RockShox Judy de sensación más suave con bloqueo, frenos de disco hidráulicos Shimano y un tren de transmisión simple 1x que abandona el desviador delantero para un menor desorden y una operación más fácil. No se preocupe, con el cassette de rango amplio 11-46, todavía obtiene todos los engranajes que necesita para subir y subir pendientes.",
        previousPrice: 2190000,
        price: 2599900,
        storeLogo: require('../assets/images/StoresLogo/BikeHouse.png') ,
        store: "bikehouse",
        gallery: [
            require('../assets/images/Marlin7/Marlin7-1.webp'),
            require('../assets/images/Marlin7/galeria1.webp'),
            require('../assets/images/Marlin7/galeria2.webp'),
            require('../assets/images/Marlin7/galeria3.webp'),
            require('../assets/images/Marlin7/galeria4.webp'),
            require('../assets/images/Marlin7/galeria5.webp'),
            require('../assets/images/Marlin7/galeria6.webp'),
        ],
    },
    {
        image: require('../assets/images/Allez/allez.webp'),
        name: "Specialized Allez",
        category: "bicicleta",
        description: "Cuatro décadas después de lanzar la primera Specialized Allez a la carretera, traemos su mejor versión hasta ahora. La más ligera de su clase*, ofrece más confianza, versatilidad y rendimiento que nunca, a más ciclistas que nunca. Tanto si buscas un aluminio de primera calidad, como si quieres una bicicleta para los fines de semana y los desplazamientos rápidos, o si acabas de empezar a montar por carretera, el rendimiento en carretera empieza con la Allez. La más ligera de su clase con un aluminio E5 de primera calidad con doble conificado, el cuadro de la Allez pesa tan solo 1.375** gramos para ofrecer una sensación rápida y ágil en carretera. Además, la horquilla carbono reduce aún más el peso (no hay tubo de dirección de aluminio oculto aquí) al tiempo que ayuda a suavizar la conducción. Y con unas opciones de construcción modernas y bien pensadas, no es de extrañar que la Allez sea también la más ligera de su clase.",
        previousPrice: 3990000,
        price: 3150000,
        storeLogo: require('../assets/images/StoresLogo/specialized.jpg') ,
        store: "specialized",
        gallery: [
            require('../assets/images/Allez/allez.webp'),
            require('../assets/images/Allez/galeria1.webp'),
            require('../assets/images/Allez/galeria2.webp'),
            require('../assets/images/Allez/galeria3.webp'),
            require('../assets/images/Allez/galeria4.webp'),
            require('../assets/images/Allez/galeria5.webp'),
        ],
    },
    {
        image: require('../assets/images/CascoBell/cascobell.jpg'),
        name: "Casco Bell Z20 GHOST MIPS",
        category: "accesorio",
        description: "Fabricado con una capa de pintura reflectante y duradera bajo la capa de pintura transparente. El Z20 Ghost brilla con intensidad cuando le golpea luz directa. El Z20 es el resultado de años de análisis sobre cómo los cascos se ajustan a la cabeza, optimizando la aerodinámica, revisando los datos de las pruebas de laboratorio, recopilando comentarios de usuarios y aplicando nuestro conocimiento acumulativo de protección ante impactos. Nuestro exclusivo sistema de gestión de energía por medio de capas progresivas, utiliza dos capas separadas de espuma EPS con diferentes densidades, con el objetivo de proteger al usuario ante diferentes velocidades de impacto. Adicionalmente cuenta con la tecnología MIPS para protección ante impactos multi-direccionales. Lo anterior permite mejorar el rendimiento ante el impacto y al mismo tiempo, ofrece un diseño general más compacto, completo, y una ventilación maximizada.",
        previousPrice: 0,
        price: 889900,
        storeLogo: require('../assets/images/StoresLogo/bell.png') ,
        store: "bell",
        gallery: [
            require('../assets/images/CascoBell/cascobell.jpg'),
            require('../assets/images/CascoBell/galeria1.jpg'),
            require('../assets/images/CascoBell/galeria2.jpg'),
            require('../assets/images/CascoBell/galeria3.jpg'),
            require('../assets/images/CascoBell/galeria4.jpg'),
            require('../assets/images/CascoBell/galeria5.jpg'),
        ],
    },
    {
        image: require('../assets/images/LEDblinder/blinderoad.webp'),
        name: "Luces LED Blinder Road 400",
        category: "accesorio",
        description: "Combinando un diseño liviano, ángulos de haz cuidadosamente considerados, una potente salida de luz y un sistema de montaje único, la luz delantera para bicicleta Blinder Road 400 es una de las luces de carretera más potentes y perfectas de Knog.",
        previousPrice: 467863,
        price: 350885,
        storeLogo: require('../assets/images/StoresLogo/knog.png') ,
        store: "knog",
        gallery: [
            require('../assets/images/LEDblinder/blinderoad.webp'),
            require('../assets/images/LEDblinder/galeria1.webp'),
            require('../assets/images/LEDblinder/galeria2.webp'),
            require('../assets/images/LEDblinder/galeria3.webp'),
            require('../assets/images/LEDblinder/galeria4.webp'),
        ],
    },
    {
        image: require('../assets/images/AttackBib/attackbib.webp'),
        name: "Pearl Izumi Men's Attack Bib Shorts",
        category: "prenda",
        description: "Descubra la comodidad y el soporte que ofrece nuestro culotte con tirantes Attack, un excelente punto de partida para cualquier ciclista dedicado. Fabricado con un tejido de punto de poliéster suave y bandas elásticas de perfil bajo en las piernas, este culotte con tirantes ofrece un equilibrio óptimo entre movilidad y compresión. La badana avanzada ELITE Levitate ofrece una amortiguación de doble densidad que proporciona un soporte elevado para la estructura ósea a la vez que mantiene el flujo de aire y la circulación. Consigue un par para tu próximo recorrido de larga distancia o una salida rápida después del trabajo.",
        previousPrice: 0,
        price: 520100,
        storeLogo: require('../assets/images/StoresLogo/pearlizumi.png') ,
        store: "pearl izumi",
        gallery: [
            require('../assets/images/AttackBib/attackbib.webp'),
            require('../assets/images/AttackBib/galeria1.webp'),
            require('../assets/images/AttackBib/galeria2.webp'),
            require('../assets/images/AttackBib/galeria3.webp'),
            require('../assets/images/AttackBib/galeria4.webp'),
            require('../assets/images/AttackBib/galeria5.webp'),
            require('../assets/images/AttackBib/galeria6.webp'),
            require('../assets/images/AttackBib/galeria7.webp'),
        ],
    },
]